name: Build and Deploy the App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          cd apps/spa
          npm install
          npm run build
          mv dist/emulator dist/release/
          echo "dwx24.samples.piral.cloud" > dist/release/CNAME
          cp dist/release/index.html dist/release/404.html
          cd ../..

      - name: Deploy Website
        run: |
          npm i gh-pages -g
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          gh-pages -d "apps/spa/dist/release" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
